// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/marwan2023nn-coder/sofa/server/public/pluginapi/experimental/bot (interfaces: Bot)

// Package mock_bot is a generated GoMock package.
package mock_bot

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/marwan2023nn-coder/sofa/server/public/model"
)

// MockBot is a mock of Bot interface.
type MockBot struct {
	ctrl     *gomock.Controller
	recorder *MockBotMockRecorder
}

// MockBotMockRecorder is the mock recorder for MockBot.
type MockBotMockRecorder struct {
	mock *MockBot
}

// NewMockBot creates a new mock instance.
func NewMockBot(ctrl *gomock.Controller) *MockBot {
	mock := &MockBot{ctrl: ctrl}
	mock.recorder = &MockBotMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBot) EXPECT() *MockBotMockRecorder {
	return m.recorder
}

// Ensure mocks base method.
func (m *MockBot) Ensure(arg0 *model.Bot, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ensure", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ensure indicates an expected call of Ensure.
func (mr *MockBotMockRecorder) Ensure(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ensure", reflect.TypeOf((*MockBot)(nil).Ensure), arg0, arg1)
}

// SofaUserID mocks base method.
func (m *MockBot) SofaUserID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SofaUserID")
	ret0, _ := ret[0].(string)
	return ret0
}

// SofaUserID indicates an expected call of SofaUserID.
func (mr *MockBotMockRecorder) SofaUserID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SofaUserID", reflect.TypeOf((*MockBot)(nil).SofaUserID))
}

// String mocks base method.
func (m *MockBot) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockBotMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockBot)(nil).String))
}
